import { CampaignDto } from '../campaign.dto';
import { PickType } from '@nestjs/swagger';

export class CreateReviewCampaignDto extends PickType(CampaignDto, [
  'guideName',
  'name',
  'description',
  'imageToDisplay',
  'type',
  'note',
  'compensationAccount',
  'budget',
  'reward',
  'countReservationDays',
  'agreementObjects',
  'usersLegalNotice',
  'commissionAgreement',
  'requirements',
  'userRequirements',
  'requiredObject',
  'blacklistUsers',
  'whitelistUsers',
  'matchBots',
  'frequencyAssign',
  'reservationTimetable',
  'app',
  'expiredAt',
  'stoppedAt',
  'currency',
  'payoutToken',
  'qualifiedPayoutToken',
  'reach',
  'timezone',
  'objects',
]) {}
